import type { Metadata } from "next";

export const metadata: Metadata = {
  title: "Evaluation of AADL 3",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: Readonly<{ children: React.ReactNode }>) {
  return (
    <html lang="ar" dir="rtl">
      <body>
        {children}
      </body>
    </html>
  );
}
